name: Check Tokens

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch if different
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Check WAKATIME_API_KEY
      run: |
        if [[ -z "${{ secrets.WAKATIME_API_KEY }}" ]]; then
          echo "WAKATIME_API_KEY is not set."
          exit 1
        else
          echo "WAKATIME_API_KEY is set."
        fi

    - name: Check GH_TOKEN
      run: |
        if [[ -z "${{ secrets.GH_TOKEN }}" ]]; then
          echo "GH_TOKEN is not set."
          exit 1
        else
          echo "GH_TOKEN is set."
        fi


